version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: drone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

#    volumes:
#      - ./db-data/:/var/lib/postgresql/data/